/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as MapRouteImport } from './routes/map'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SofiaIndexRouteImport } from './routes/sofia/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as SofiaNeighborhoodRouteImport } from './routes/sofia/$neighborhood'
import { Route as EnScoreRouteImport } from './routes/en/score'
import { Route as EnMapRouteImport } from './routes/en/map'
import { Route as EnEmbedRouteImport } from './routes/en/embed'
import { Route as EnCompareRouteImport } from './routes/en/compare'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as ApiSitemapRouteImport } from './routes/api/sitemap'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as EnSofiaIndexRouteImport } from './routes/en/sofia/index'
import { Route as EnSofiaNeighborhoodRouteImport } from './routes/en/sofia/$neighborhood'

const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SofiaIndexRoute = SofiaIndexRouteImport.update({
  id: '/sofia/',
  path: '/sofia/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const SofiaNeighborhoodRoute = SofiaNeighborhoodRouteImport.update({
  id: '/sofia/$neighborhood',
  path: '/sofia/$neighborhood',
  getParentRoute: () => rootRouteImport,
} as any)
const EnScoreRoute = EnScoreRouteImport.update({
  id: '/en/score',
  path: '/en/score',
  getParentRoute: () => rootRouteImport,
} as any)
const EnMapRoute = EnMapRouteImport.update({
  id: '/en/map',
  path: '/en/map',
  getParentRoute: () => rootRouteImport,
} as any)
const EnEmbedRoute = EnEmbedRouteImport.update({
  id: '/en/embed',
  path: '/en/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const EnCompareRoute = EnCompareRouteImport.update({
  id: '/en/compare',
  path: '/en/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapRoute = ApiSitemapRouteImport.update({
  id: '/api/sitemap',
  path: '/api/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSofiaIndexRoute = EnSofiaIndexRouteImport.update({
  id: '/en/sofia/',
  path: '/en/sofia/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSofiaNeighborhoodRoute = EnSofiaNeighborhoodRouteImport.update({
  id: '/en/sofia/$neighborhood',
  path: '/en/sofia/$neighborhood',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/embed': typeof EmbedRoute
  '/map': typeof MapRoute
  '/score': typeof ScoreRoute
  '/api/og': typeof ApiOgRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/en/about': typeof EnAboutRoute
  '/en/compare': typeof EnCompareRoute
  '/en/embed': typeof EnEmbedRoute
  '/en/map': typeof EnMapRoute
  '/en/score': typeof EnScoreRoute
  '/sofia/$neighborhood': typeof SofiaNeighborhoodRoute
  '/en/': typeof EnIndexRoute
  '/sofia/': typeof SofiaIndexRoute
  '/en/sofia/$neighborhood': typeof EnSofiaNeighborhoodRoute
  '/en/sofia/': typeof EnSofiaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/embed': typeof EmbedRoute
  '/map': typeof MapRoute
  '/score': typeof ScoreRoute
  '/api/og': typeof ApiOgRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/en/about': typeof EnAboutRoute
  '/en/compare': typeof EnCompareRoute
  '/en/embed': typeof EnEmbedRoute
  '/en/map': typeof EnMapRoute
  '/en/score': typeof EnScoreRoute
  '/sofia/$neighborhood': typeof SofiaNeighborhoodRoute
  '/en': typeof EnIndexRoute
  '/sofia': typeof SofiaIndexRoute
  '/en/sofia/$neighborhood': typeof EnSofiaNeighborhoodRoute
  '/en/sofia': typeof EnSofiaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/embed': typeof EmbedRoute
  '/map': typeof MapRoute
  '/score': typeof ScoreRoute
  '/api/og': typeof ApiOgRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/en/about': typeof EnAboutRoute
  '/en/compare': typeof EnCompareRoute
  '/en/embed': typeof EnEmbedRoute
  '/en/map': typeof EnMapRoute
  '/en/score': typeof EnScoreRoute
  '/sofia/$neighborhood': typeof SofiaNeighborhoodRoute
  '/en/': typeof EnIndexRoute
  '/sofia/': typeof SofiaIndexRoute
  '/en/sofia/$neighborhood': typeof EnSofiaNeighborhoodRoute
  '/en/sofia/': typeof EnSofiaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/compare'
    | '/embed'
    | '/map'
    | '/score'
    | '/api/og'
    | '/api/sitemap'
    | '/en/about'
    | '/en/compare'
    | '/en/embed'
    | '/en/map'
    | '/en/score'
    | '/sofia/$neighborhood'
    | '/en/'
    | '/sofia/'
    | '/en/sofia/$neighborhood'
    | '/en/sofia/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/compare'
    | '/embed'
    | '/map'
    | '/score'
    | '/api/og'
    | '/api/sitemap'
    | '/en/about'
    | '/en/compare'
    | '/en/embed'
    | '/en/map'
    | '/en/score'
    | '/sofia/$neighborhood'
    | '/en'
    | '/sofia'
    | '/en/sofia/$neighborhood'
    | '/en/sofia'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/compare'
    | '/embed'
    | '/map'
    | '/score'
    | '/api/og'
    | '/api/sitemap'
    | '/en/about'
    | '/en/compare'
    | '/en/embed'
    | '/en/map'
    | '/en/score'
    | '/sofia/$neighborhood'
    | '/en/'
    | '/sofia/'
    | '/en/sofia/$neighborhood'
    | '/en/sofia/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompareRoute: typeof CompareRoute
  EmbedRoute: typeof EmbedRoute
  MapRoute: typeof MapRoute
  ScoreRoute: typeof ScoreRoute
  ApiOgRoute: typeof ApiOgRoute
  ApiSitemapRoute: typeof ApiSitemapRoute
  EnAboutRoute: typeof EnAboutRoute
  EnCompareRoute: typeof EnCompareRoute
  EnEmbedRoute: typeof EnEmbedRoute
  EnMapRoute: typeof EnMapRoute
  EnScoreRoute: typeof EnScoreRoute
  SofiaNeighborhoodRoute: typeof SofiaNeighborhoodRoute
  EnIndexRoute: typeof EnIndexRoute
  SofiaIndexRoute: typeof SofiaIndexRoute
  EnSofiaNeighborhoodRoute: typeof EnSofiaNeighborhoodRoute
  EnSofiaIndexRoute: typeof EnSofiaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sofia/': {
      id: '/sofia/'
      path: '/sofia'
      fullPath: '/sofia/'
      preLoaderRoute: typeof SofiaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sofia/$neighborhood': {
      id: '/sofia/$neighborhood'
      path: '/sofia/$neighborhood'
      fullPath: '/sofia/$neighborhood'
      preLoaderRoute: typeof SofiaNeighborhoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/score': {
      id: '/en/score'
      path: '/en/score'
      fullPath: '/en/score'
      preLoaderRoute: typeof EnScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/map': {
      id: '/en/map'
      path: '/en/map'
      fullPath: '/en/map'
      preLoaderRoute: typeof EnMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/embed': {
      id: '/en/embed'
      path: '/en/embed'
      fullPath: '/en/embed'
      preLoaderRoute: typeof EnEmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/compare': {
      id: '/en/compare'
      path: '/en/compare'
      fullPath: '/en/compare'
      preLoaderRoute: typeof EnCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap': {
      id: '/api/sitemap'
      path: '/api/sitemap'
      fullPath: '/api/sitemap'
      preLoaderRoute: typeof ApiSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/sofia/': {
      id: '/en/sofia/'
      path: '/en/sofia'
      fullPath: '/en/sofia/'
      preLoaderRoute: typeof EnSofiaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/sofia/$neighborhood': {
      id: '/en/sofia/$neighborhood'
      path: '/en/sofia/$neighborhood'
      fullPath: '/en/sofia/$neighborhood'
      preLoaderRoute: typeof EnSofiaNeighborhoodRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompareRoute: CompareRoute,
  EmbedRoute: EmbedRoute,
  MapRoute: MapRoute,
  ScoreRoute: ScoreRoute,
  ApiOgRoute: ApiOgRoute,
  ApiSitemapRoute: ApiSitemapRoute,
  EnAboutRoute: EnAboutRoute,
  EnCompareRoute: EnCompareRoute,
  EnEmbedRoute: EnEmbedRoute,
  EnMapRoute: EnMapRoute,
  EnScoreRoute: EnScoreRoute,
  SofiaNeighborhoodRoute: SofiaNeighborhoodRoute,
  EnIndexRoute: EnIndexRoute,
  SofiaIndexRoute: SofiaIndexRoute,
  EnSofiaNeighborhoodRoute: EnSofiaNeighborhoodRoute,
  EnSofiaIndexRoute: EnSofiaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
